config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'user/:id/edit' => 'users#edit', as: :edit_user
  patch 'user/:id' => 'users#update', as: :update_user
  delete 'user/withdraw' => 'users#withdraw'
  get 'user/unsubscribe' => 'users#unsubscribe'
  get 'user/my_page' => 'users#show'

  get 'inquiries/new'
  post 'inquiries/create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'

  get '/expenses_list' => 'expenses#list'
  get '/expenses_album' => 'expenses#album'

  post 'favorite/:id' => 'favorites#create', as: 'create_favorite'
  delete 'favorite/:id' => 'favorites#destroy', as: 'destroy_favorite'
  #get '/expenses_favorite' => 'favorites#index', on: :collection
  get 'expenses_aggregate' => 'expenses#aggregate', as: 'expense_aggregate'
  resources :expenses do
    #resource :favorites, only: [:create, :destroy]
    get '/expenses_favorite' => 'favorites#index', on: :collection
    get :search, on: :collection
  end




  #resources :users, only: [:show, :edit, :update]
  #resources :genres, only: [:index, :create, :edit, :update]
  #resources :aggregates, only: [:index, :create, :update]



end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :expense
  #belongs_to :user, optional: true
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  #before_action :authenticate_user!
  before_action :set_expense, except: :index

  def create
    expense = Expense.find(params[:id])

    #favorite = current_user.favorites.new(expense_id: expense.id)
    #favorite.save
    Favorite.create(expense_id: params[:id])
    #expense_id.user_id = current_user.id
  end

  def destroy
    #expense = Expense.find(params[:id])
    #favorite = current_user.favorites.find_by(expense_id: expense.id)
    #favorite.destroy
    Favorite.find_by(expense_id: params[:id]).destroy
  end


  def index

    #user_id = current_user.id
    #expense2 = Expense.where(user_id: user_id)

    #expense3 = Expense.find_by(expense_id: expense2)


    #@expense = Expense.where(user_id: current_user.id)
    #favorites = Favorite.pluck([:user_id][:expense_id])

    #@favorite_list = Expense.where(user_id: current_user.id).find(Favorite.pluck(:expense_id))
    @favorite_list = Expense.where(user_id: current_user.id).joins(:favorite)

    #redirect_to root_path unless current_user.id == @user

    #favorites = Favorite.pluck(:expense_id)
    #@favorite_list = Expense.find(favorites)
  end

  private
    def set_expense
      @expense = Expense.find(params[:id])
    end

end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_like.html.erb
<% if expense.favorited_by? %>
    <%#=link_to expense_favorites_path(expense_id: expense.id, id: expense.id), method: :delete, remote: true do%>
    <%= link_to destroy_favorite_path(expense), method: :delete, remote: true do %>

      <i class="fas fa-star"></i>
    <% end %>

<% else %>
    <%=link_to create_favorite_path(expense), method: :post, remote: true do %>
      <i class="far fa-star" aria-hidden="true"></i>
    <% end %>
<% end%>

app/views/favorites/create.js.erb
$('#likes_buttons_<%= @expense.id %>').html("<%= j(render 'favorites/like', expense: @expense) %>");

app/views/favorites/destroy.js.erb
$('#likes_buttons_<%= @expense.id %>').html("<%= j(render 'favorites/like', expense: @expense) %>");

app/views/favorites/index.html.erb
<div class="container">
  <div class="row">
   <h5><div class = "bg-light mt-4 col-12 md-6">
       お気に入り</div></h5>
   </div>
<center>
<div class="d-flex flex-row flex-wrap mx-5 mt-5">
<% if @favorite_list.present? %>
    <% @favorite_list.each do |expense| %>
    <div class="card  shadow-lg">
        <div class="d-flex flex-row flex-column flex-wrap">
    <%= link_to expense_path(expense.id) do %>
    <%= attachment_image_tag expense, :image, :fill, 300, 300, format: 'jpeg', fallback: "" %>
    <% end %>
    <p>¥<%= expense.expense %></p>
    <p><%= truncate(expense.memo, length: 18,　omission: "…") %></p>
    </div>
    </div>

    <% end %>
<% end %>
</div>
</center>