config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'user/:id/edit' => 'users#edit', as: :edit_user
  patch 'user/:id' => 'users#update', as: :update_user
  delete 'user/withdraw' => 'users#withdraw'
  get 'user/unsubscribe' => 'users#unsubscribe'
  get 'user/my_page' => 'users#show'

  get 'inquiries/new'
  post 'inquiries/create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'

  get '/expenses_list' => 'expenses#list'
  get '/expenses_album' => 'expenses#album'

  post 'favorite/:id' => 'favorites#create', as: 'create_favorite'
  delete 'favorite/:id' => 'favorites#destroy', as: 'destroy_favorite'
  #get '/expenses_favorite' => 'favorites#index', on: :collection
  get 'expenses_aggregate' => 'expenses#aggregate', as: 'expense_aggregate'
  resources :expenses do
    #resource :favorites, only: [:create, :destroy]
    get '/expenses_favorite' => 'favorites#index', on: :collection
    get :search, on: :collection
  end




  #resources :users, only: [:show, :edit, :update]
  #resources :genres, only: [:index, :create, :edit, :update]
  #resources :aggregates, only: [:index, :create, :update]



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :expense, dependent: :destroy

  #has_many :favorites, dependent: :destroy

  validates :nickname, {presence:true, length: {minimum:2, maximum: 20}, uniqueness: true}


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!, except: [:withdraw]

  def show
    @user = current_user
  end

  def edit
    @user = current_user

    if @user == current_user
      render "edit"
    else
      redirect_to "/"
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)

    redirect_to user_my_page_path
    else
    render :edit
    end
  end


  def unsubscribe
    @user = current_user
  end

  def withdraw
    #user = User.find(params[:id])
    @user = current_user
    @user.destroy
    reset_session
    redirect_to root_path, alert: "ご利用誠にありがとうございました。"

  end

  private

  def user_params
    params.require(:user).permit(:nickname, :email)
  end



end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
  <center>

   <h5><div class = "bg-light mt-4 col-2 mx-6">
      ニックネームの変更
    </div>
    </div>
<%= form_with model: @user, url: update_user_path, local:true do |f| %>

  <%= f.text_field :nickname %>

  <%= f.submit '名前の変更する', class: 'btn btn-success' %>


<% end %>

app/views/users/show.html.erb
<div class="container">
<div class ="row">
    <div class="mt-5 mx-3">
    <p><strong>
    ようこそ、<%= @user.nickname %>さん</strong></p></div>
    </div>
<div class ="row">
<div class="mt-3">

<%= link_to "ニックネームを変更する", edit_user_path(@user), class: "btn btn-outline-success" %>
<%#= link_to "パスワード変更する", edit_user_password_path %>

<%= link_to "退会する", user_unsubscribe_path, class: 'btn btn-outline-danger' %>
</div>
</div>
</div>

app/views/users/unsubscribe.html.erb
<center>
<div class="mt-5">
<p><strong>本当に退会しますか？</strong></p></div>
<div class="mt-5">
<p>退会すると、</p>
<p>これまでの投稿が閲覧できなくなります。</p>
<p>退会する場合は、「退会」するをクリックしてください。</p>
<div class="mt-3">
<%= link_to "退会しない",  user_my_page_path(current_user), class: 'btn btn-primary' %>
<%= link_to "退会する", user_withdraw_path(current_user), method: :delete, class: 'btn btn-danger' %>
</div>
</div>
</center>