config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'user/:id/edit' => 'users#edit', as: :edit_user
  patch 'user/:id' => 'users#update', as: :update_user
  delete 'user/withdraw' => 'users#withdraw'
  get 'user/unsubscribe' => 'users#unsubscribe'
  get 'user/my_page' => 'users#show'

  get 'inquiries/new'
  post 'inquiries/create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'

  get '/expenses_list' => 'expenses#list'
  get '/expenses_album' => 'expenses#album'

  post 'favorite/:id' => 'favorites#create', as: 'create_favorite'
  delete 'favorite/:id' => 'favorites#destroy', as: 'destroy_favorite'
  #get '/expenses_favorite' => 'favorites#index', on: :collection
  get 'expenses_aggregate' => 'expenses#aggregate', as: 'expense_aggregate'
  resources :expenses do
    #resource :favorites, only: [:create, :destroy]
    get '/expenses_favorite' => 'favorites#index', on: :collection
    get :search, on: :collection
  end




  #resources :users, only: [:show, :edit, :update]
  #resources :genres, only: [:index, :create, :edit, :update]
  #resources :aggregates, only: [:index, :create, :update]



end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController

  before_action :authenticate_user!

  def new
    @expense = Expense.new

  end

  def create
    @expense = Expense.new(expense_params)
    @expense.user_id = current_user.id
    #@expense.genre_id = 1
    if @expense.save
      redirect_to expenses_path
    else
      render :new
    end

  end

  def index

      #@expense.user_id = Expense.current_user.id
      #@expenses = current_user.expenses.all
      #@today = Date.new(year, month, day)today
      @today = Date.today
      if params[:month].present?
        monthSelected = params[:month].split("-")
        year = monthSelected[0].to_i
        month = monthSelected[1].to_i
        @today = Date.new(year, month)
      end
      from_date = Date.new(@today.year, @today.month, @today.beginning_of_month.day).beginning_of_week(:sunday)
      to_date = Date.new(@today.year, @today.month, @today.end_of_month.day).end_of_week(:sunday)
      @calendar_data = from_date.upto(to_date)
      @previous =  Expense.get_previous_month(@today)

      @next = Expense.get_next_month(@today)



      #@expense = Expense.find_by(date: )
      #@expense = Expense.find_by(params[:date])
      #@expenses =Expense.all



  end

  def search
    if params[:search] != ""
      #@expenses =  Expense.where("memo LIKE(?)","%#{params[:search]}%")
      @expenses =  Expense.where(user_id: current_user.id).where("memo LIKE(?)","%#{params[:search]}%")
    else
      #@expenses = Expense.all
      @expenses = current_user.expense.all
    end

  end



  def show


    @date = @calendar_data

    @expense =Expense.find(params[:id])
    #@expense.user_id = current_user.id
    #@expenses = Expense.where(date: @expense.date)
    @expenses = Expense.where(user_id: current_user.id).where(date: @expense.date)

    redirect_to root_path unless current_user.id == @expense.user_id

  end

  def edit
    @expense = Expense.find(params[:id])
    #if @user == current_user
      #render :edit
    #else
      #redirect_to "/"
   # end


  end

  def update
    @expense = Expense.find(params[:id])
    @expense.update(expense_params)
    if @expense.save
      redirect_to expense_path(@expense.id)
    else
      render :edit
    end
  end

  def destroy
    expense = Expense.find(params[:id])
    expense.destroy
    redirect_to expenses_path
  end

  def list

    @expenses = current_user.expense.all
  end

  def album

    @expenses = current_user.expense.all
  end

  def aggregate
    #@expense = Expense.select("date").group("date").sum("expense")

    @thisWeekSum =  Expense.where(user_id: current_user.id).where(date: (Date.today - (Date.today.wday))..Date.today).sum(:expense)
    @lastWeekSum =  Expense.where(user_id: current_user.id).where(date: (Date.today - (Date.today.wday) - 7)..(Date.today - (Date.today.wday) - 1)).sum(:expense)
    @monthSum = Expense.where(user_id: current_user.id).where(date: Date.today.beginning_of_month..Date.today.end_of_month).sum(:expense)
    @aggregate = Expense.where(user_id: current_user.id).where(date: Date.today.prev_month.beginning_of_month..Date.today.prev_month.end_of_month).sum(:expense)
  end




  private
    def expense_params
      params.require(:expense).permit(:user_id, :genre_id, :expense, :image, :memo, :target_month, :date)
    end

end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/expenses/aggregate.html.erb
<div class="container">
  <div class="row">
   <h5><div class = "bg-light mt-4 col-12 md-6">
       レポート</div></h5>
  </div>

   <div class="mt-5 col-12  mx-2">
    <div class ="row">
    <label for="" class="col-2 mb-4 text-center btn btn-secondary">今週</label>
    <div class="col-10">計￥<%= @thisWeekSum %>の出費</div>
   </div>


    <div class ="row">
    <label for="" class="col-sm-2 mb-4 text-center btn btn-secondary">先週</label>
    <div class="col-sm-8">計￥<%= @lastWeekSum %>の出費</div>
   </div>


    <div class ="row">
    <label for="" class="col-sm-2 mb-4 text-center btn btn-secondary">今月</label>
    <div class="col-sm-8">計￥<%= @monthSum %>の出費</div>
   </div>


    <div class ="row">
    <label for="" class="col-sm-2 mb-4 text-center btn btn-secondary">先月</label>
    <div class="col-sm-8">計￥<%= @aggregate  %>の出費</div>
   </div>



</div>
</div>

app/views/expenses/album.html.erb
<div class="container">
  <div class="row">
   <h5><div class = "bg-light mt-4 col-12 md-6">
       アルバム</div></h5>
   </div>
<center>

<div class="d-flex flex-row flex-wrap mx-5 mt-5">
<% @expenses.each do |expense| %>
<div class="card  shadow-lg">
<div class="d-flex flex-row flex-column flex-wrap">
   <%= link_to expense_path(expense.id) do %>
     <%= attachment_image_tag expense, :image, :fill, 200, 200, format: 'jpeg', fallback: "" %>
   <% end %>
</div>
</div>
 <% end %>

 </div>
</center>

app/views/expenses/edit.html.erb
<div class="container">
  <center>
   <h5><div class = "bg-light mt-4 col-2 mx-6">
    編集</div></h5>
    </center>
    <div class="row">
    <div class="mt-5 col-12  mx-6">
 <%= form_with model: @expense, url: expense_path, local:true do |f| %>

<div class ="row">
    <label for="id" class="col-sm-4 mb-4 text-right">出費</label>
    <div class="col-sm-8">
   ¥<%= f.text_field :expense, autofocus:true, id:"inputExpense",placeholder:"Expense" %></div>
  </div>


  <div class ="row">
    <label for="id" class="col-sm-4 mb-4 text-right">写真</label>
      <div class="mx-3">
       <div class="item_image_btn">
   <%= f.attachment_field :image, id: "file" %></div>
   <div id="img_field" onClick="$('#file').click()" >
    画像選択
    </div>
  </div>
  </div>

  <div class ="row">
    <label for="id" class="col-sm-4 mb-4 text-right">備考</label>
    <div class="col-sm-8">
   <%= f.text_area :memo, autofocus:true, id:"inputMemo", placeholder:"メモ" %>
   </div>
    </div>

    <div class ="row mt-3">
    <label for="id" class="col-sm-4 mb-4 text-right"></label>
    <div class="col-sm-8">
   <%= f.submit "変更を保存", class: "btn btn-outline-success" %></div>
  </div>
  </div>

 <% end %>

app/views/expenses/index.html.erb
<meta name="viewport" content="width=device-width,initial-scale=1.0">





<center>


<div class=container>
  <div class="row">
<div class="col-3 mt-5">
    <form action="/expenses" method="get">
      <input type="hidden" name="month" value=<%=@previous%>>
      <button class="btn btn-outline-secondary">＜</button>
    </form>
  </div>
  <div class="col-6 mt-5 mx-0 ">
<%= @today.strftime(" %Y年%-m月 ") %>
</div>

<div class="col-3 mt-5 mx-0">
      <form action="/expenses" method="get">
        <input type="hidden" name="month" value=<%=@next%>>
        <button class="btn btn-outline-secondary">＞</button>
      </form>
   </div>
</div>
</div>
<table width="80%">

  <thead class="text-dark bg-light">
  <tr>
    <% t('date.abbr_day_names').each do |day_name| %>
      <td>

        <%= day_name %>

      </td>
    <% end %>
  </tr>

  </thead>


  <% @calendar_data.each do |date| %>

      <% if expense = Expense.where(user_id: current_user.id).where(date: date).empty? %>
        <% if date.wday == 0 %>
          <tr>
        <% end %>

        <td style="vertical-align: top;">

          <%= date.day %>


        </td>


        <% if date.wday == 6 %>
        </tr>
        <% end %>　　　　　<%#空白表示 %>

      <% else %>
        <% if Expense.where(user_id: current_user.id).expense_image(date) %>
            <% if date.wday == 0 %>
              <tr>
            <% end %>
            <td style="vertical-align: top;">
              <%= date.day %>

              <%= link_to expense_path(Expense.where(user_id: current_user.id).find_by(date: date).id) do %>
              <%#= link_to expenses_detail_path do %>
              <div class="image">
              <%= attachment_image_tag Expense.where(user_id: current_user.id).find_by(date: date), :image, :fill, 50, 50 %>
              </div>
              <% end %>
              <%#= link_to "show", expense_path(expense.id) %>

            </td>
            <% if date.wday == 6 %>
            </tr>
            <% end %>


        <% else %>
            <% if date.wday == 0 %>
              <tr>
            <% end %>

            <td style="vertical-align: top;">
              <%= date.day %>
              <%= link_to expense_path(Expense.where(user_id: current_user.id).find_by(date: date).id) do %>

            　¥<%= expense = Expense.where(user_id: current_user.id).where(date: date).sum(:expense) %>

            　<% end %>
            </td>

            <% if date.wday == 6 %>
            </tr>
            <% end %>
        <% end %>
      <% end %>
  <% end %>

</table>
    <div class="mt-5">
    <form action="/expenses" method="get">
      <input type="month" name="month">
      <button class="btn btn-outline-secondary">月を変える</button>
    </form>
  </div>
  </div>

</div>
</div>
</center>

app/views/expenses/list.html.erb
<div class="container">
  <div class="row">
   <h5><div class = "bg-light mt-4 col-12 md-6">
       出金リスト</div></h5>
   </div>
<div class="card-list-container py-5">

  <% @expenses.each do |expense| %>
   <div class="card w-60 mx-auto mt-4 shadow-lg">
    <div class="card-body">
      <div class="row">

       <div class="col-2"><%= expense.date.strftime(" %Y年%-m月%-d日 ") %></div>
       <div class="col-2">¥<%= expense.expense %></div>
       <div class="col-6"><%= truncate(expense.memo, length: 18,　omission: "…") %></div>
       <div class="col-2"><%= link_to "詳細",expense_path(expense.id), class: "btn btn-secondary" %></div>
      </div>
    </div>
  </div>
   <% end %>
</div>

app/views/expenses/new.html.erb
<div class="container">
  <center>

   <h5><div class = "bg-light mt-4 col-2 mx-6">
    メモ</div></h5>

    </center>

 <div class="mt-5 col-12  mx-6">
<%= form_with model: @expense, local:true do |f| %>

<div class ="row">
    <label for="id" class="col-sm-4 mb-4 text-right">出費</label>
    <div class="col-sm-8">
  ￥<%= f.text_field :expense %></div>
  </div>

  <div class ="row">
    <label for="id" class="col-sm-4 mb-4 text-right">写真</label>
      <div class="mx-3">
       <div class="item_image_btn">
        <%= f.attachment_field :image, id: "file" %></div>
   <div id="img_field" onClick="$('#file').click()" >
    画像選択
    </div>
  </div>
  </div>

  <div class ="row">
    <label for="id" class="col-sm-4 mb-4 text-right">備考</label>
    <div class="col-sm-8">
   <%= f.text_area :memo %></div>
    </div>
  <div class ="row mt-2">
    <label for="id" class="col-sm-4 mb-4 text-right">日付</label>
    <div class="col-sm-8">
   <%= f.date_field :date%>
   </div>
  </div>
  <div class ="row mt-3">
    <label for="id" class="col-sm-4 mb-4 text-right"></label>
    <div class="col-sm-8">
  <%= f.submit 'メモする', class: "btn btn-outline-secondary" %> </div>
  </div>
<% end %>

</div>
</div>
</div>

app/views/expenses/search.html.erb
<center>


<table>

<div class="mt-3">
<% @expenses.each do |expense| %>


    <tr class="shadow-lg">
    <td>
    <%= link_to expense_path(expense.id) do %>
      <%= attachment_image_tag expense, :image, :fill, 300, 300, format: 'jpeg', fallback: "" %>
    <% end %>
    </td>

    <td>
    <center>
    <%= expense.date.strftime(" %Y年%-m月%-d日 ") %>
    <div class="mt-3">
    <p>¥<%= expense.expense %></p></div>
    <p><%= expense.memo %></p>

    <div id ="likes_buttons_<%= expense.id %>" >
        <%= render 'favorites/like', expense: expense %>
    </div>
    </center>

    </td>
    </tr>


<% end %>
</div>
</table>


</center>

app/views/expenses/show.html.erb
<div class="container">
  <div class="row">
   <h5><div class = "bg-light mt-4 col-12 md-6">
       メモ詳細</div></h5>
   </div>

    <center>

        <%= @expense.date.strftime(" %Y年%-m月%-d日 ") %>のメモ
    </center>
 <center>

<div class="d-flex flex-row flex-wrap mx-1 mt-5">
    <% @expenses.each do |expense| %>

      <div class="card mx-auto mt-4 shadow-lg">
      <div class="card-body">


        <%= attachment_image_tag expense, :image, :fill, 300, 300, format: 'jpeg', fallback: "20200501_noimage.jpg", size: "300x300" %>

        <div class="col">
            <h5>¥<%= expense.expense %></h5>
            <p><%= expense.memo %></p>
            <% if expense.image %>
            <div id ="likes_buttons_<%= expense.id %>" >
                <%= render 'favorites/like', expense: expense %>
            </div>
            <% end %>
            <div class="mt-3">
            <%= link_to "編集", edit_expense_path(expense), class: "btn btn-outline-secondary" %>

            <%= link_to "削除", expense_path(expense.id), method: :delete, class: "btn btn-outline-secondary" %></div>



        </div>
       </div>
       </div>
    <% end %>
</div>
</div>
</center>