config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'user/:id/edit' => 'users#edit', as: :edit_user
  patch 'user/:id' => 'users#update', as: :update_user
  delete 'user/withdraw' => 'users#withdraw'
  get 'user/unsubscribe' => 'users#unsubscribe'
  get 'user/my_page' => 'users#show'

  get 'inquiries/new'
  post 'inquiries/create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'

  get '/expenses_list' => 'expenses#list'
  get '/expenses_album' => 'expenses#album'

  post 'favorite/:id' => 'favorites#create', as: 'create_favorite'
  delete 'favorite/:id' => 'favorites#destroy', as: 'destroy_favorite'
  #get '/expenses_favorite' => 'favorites#index', on: :collection
  get 'expenses_aggregate' => 'expenses#aggregate', as: 'expense_aggregate'
  resources :expenses do
    #resource :favorites, only: [:create, :destroy]
    get '/expenses_favorite' => 'favorites#index', on: :collection
    get :search, on: :collection
  end




  #resources :users, only: [:show, :edit, :update]
  #resources :genres, only: [:index, :create, :edit, :update]
  #resources :aggregates, only: [:index, :create, :update]



end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mymemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!--<#meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">-->
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <script src="https://kit.fontawesome.com/b805f4612c.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>


  <body>
    <header class ="border-bottom">

     <% if user_signed_in? %>

        <div class="m-2">
        <%= link_to "TOP", root_path, class: 'btn btn-outline-secondary' %>
        <%=link_to "カレンダー", expenses_path, class: 'btn btn-outline-success' %>
        <%= link_to "メモ", new_expense_path, class: "btn btn-outline-primary" %>
        </div>

        <div id="sp-menu">

            <ul>


              <li><%= link_to "レポート", expense_aggregate_path %></li>
              <li><%= link_to "出金リスト", expenses_list_path %></li>
              <li><%= link_to "アルバム", expenses_album_path %></li>
              <li><%= link_to "お気に入り", expenses_favorite_expenses_path %></li>
              <li><%= link_to "お問い合わせ", inquiries_new_path %></li>
              <li><%= link_to "設定", user_my_page_path(current_user) %></li>
              <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
            </ul>

        </div>
         <div id="hm-icon">
          <span class="menu-trigger" href="#">
            <span></span>
            <span></span>
            <span></span>
          </span>
        </div>

        <div class="m-2">
        <%= form_with url: search_expenses_path, method: :get, local: true do |form| %>
          <%= form.text_field :search %>
          <%= form.submit "検索", class:"btn btn-outline-secondary" %>
        <% end %>
        </div>
      </ul>
    <% else %>
        <div class="m-2 mt-1">
        <%= link_to "TOP", root_path, class: 'btn btn-outline-secondary' %>

        <ul class= "navbar-nav ml-auto  d-inline p-2 pl-2" >
        <%= link_to "新規登録", new_user_registration_path, class: 'btn btn-outline-secondary' %>
        <%= link_to "ログイン", new_user_session_path, class: 'btn btn-outline-secondary' %>
        </ul>
        </div>


    <% end %>
  </header>

    <%= yield %>


  </body>

<footer class="border-bottom mt-3">


</footer>


</html>